apiVersion: v1
kind: Service
metadata:
  name: hellotype
  namespace: hellotype
  labels:
    app: hellotype
    service: hellotype
spec:
  ports:
  - name: http
    appProtocol: http
    port: 8000
  selector:
    app: hellotype
