apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hellotype
  labels:
    app: hellotype
rules:
- apiGroups: ["apps"]
  verbs: [ "get", "watch", "list", "update", "patch", "create", "delete" ]
  resources: [ "deployments" ]
- apiGroups: ["foo.com"]
  verbs: [ "get", "watch", "list", "update", "patch", "create", "delete" ]
  resources: [ "hellotypes" ]
