/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/jacob-delgado/demo/pkg/apis/foo/v1"
	foov1 "github.com/jacob-delgado/demo/pkg/client/applyconfiguration/foo/v1"
	scheme "github.com/jacob-delgado/demo/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// HelloTypesGetter has a method to return a HelloTypeInterface.
// A group's client should implement this interface.
type HelloTypesGetter interface {
	HelloTypes(namespace string) HelloTypeInterface
}

// HelloTypeInterface has methods to work with HelloType resources.
type HelloTypeInterface interface {
	Create(ctx context.Context, helloType *v1.HelloType, opts metav1.CreateOptions) (*v1.HelloType, error)
	Update(ctx context.Context, helloType *v1.HelloType, opts metav1.UpdateOptions) (*v1.HelloType, error)
	UpdateStatus(ctx context.Context, helloType *v1.HelloType, opts metav1.UpdateOptions) (*v1.HelloType, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.HelloType, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.HelloTypeList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.HelloType, err error)
	Apply(ctx context.Context, helloType *foov1.HelloTypeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.HelloType, err error)
	ApplyStatus(ctx context.Context, helloType *foov1.HelloTypeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.HelloType, err error)
	HelloTypeExpansion
}

// helloTypes implements HelloTypeInterface
type helloTypes struct {
	client rest.Interface
	ns     string
}

// newHelloTypes returns a HelloTypes
func newHelloTypes(c *FooV1Client, namespace string) *helloTypes {
	return &helloTypes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the helloType, and returns the corresponding helloType object, and an error if there is any.
func (c *helloTypes) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.HelloType, err error) {
	result = &v1.HelloType{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hellotypes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of HelloTypes that match those selectors.
func (c *helloTypes) List(ctx context.Context, opts metav1.ListOptions) (result *v1.HelloTypeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.HelloTypeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("hellotypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested helloTypes.
func (c *helloTypes) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("hellotypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a helloType and creates it.  Returns the server's representation of the helloType, and an error, if there is any.
func (c *helloTypes) Create(ctx context.Context, helloType *v1.HelloType, opts metav1.CreateOptions) (result *v1.HelloType, err error) {
	result = &v1.HelloType{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("hellotypes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(helloType).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a helloType and updates it. Returns the server's representation of the helloType, and an error, if there is any.
func (c *helloTypes) Update(ctx context.Context, helloType *v1.HelloType, opts metav1.UpdateOptions) (result *v1.HelloType, err error) {
	result = &v1.HelloType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hellotypes").
		Name(helloType.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(helloType).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *helloTypes) UpdateStatus(ctx context.Context, helloType *v1.HelloType, opts metav1.UpdateOptions) (result *v1.HelloType, err error) {
	result = &v1.HelloType{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("hellotypes").
		Name(helloType.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(helloType).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the helloType and deletes it. Returns an error if one occurs.
func (c *helloTypes) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hellotypes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *helloTypes) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("hellotypes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched helloType.
func (c *helloTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.HelloType, err error) {
	result = &v1.HelloType{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("hellotypes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied helloType.
func (c *helloTypes) Apply(ctx context.Context, helloType *foov1.HelloTypeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.HelloType, err error) {
	if helloType == nil {
		return nil, fmt.Errorf("helloType provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(helloType)
	if err != nil {
		return nil, err
	}
	name := helloType.Name
	if name == nil {
		return nil, fmt.Errorf("helloType.Name must be provided to Apply")
	}
	result = &v1.HelloType{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("hellotypes").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *helloTypes) ApplyStatus(ctx context.Context, helloType *foov1.HelloTypeApplyConfiguration, opts metav1.ApplyOptions) (result *v1.HelloType, err error) {
	if helloType == nil {
		return nil, fmt.Errorf("helloType provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(helloType)
	if err != nil {
		return nil, err
	}

	name := helloType.Name
	if name == nil {
		return nil, fmt.Errorf("helloType.Name must be provided to Apply")
	}

	result = &v1.HelloType{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("hellotypes").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
